import { Box, Center, Flex, Text } from "@chakra-ui/react";
import type { NextPage } from "next";
import Head from "next/head";

const Home: NextPage = () => {
	const fruits: string[] = ["apple", "banana", "grape"];

	const decideColor = (fruit: string): string => {
		if (fruit === "apple") {
			return "red";
		} else if (fruit === "banana") {
			return "yellow";
		} else {
			return "blue";
		}
	};
	return (
		<div>
			<Head>
				<title>Create Next App</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>

			<main>
				<Flex color="white" h="200px">
					{fruits.map((fruit, i) => (
						<Center bg={decideColor(fruit)} key={i} flex="1">
							<Text>I like {fruit}</Text>
						</Center>
					))}
				</Flex>
			</main>
		</div>
	);
};

export default Home;
